project_id = "wtiexyrawenxckctbwzn"

[functions.ai-agent]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-tax-calculator]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.create-guest-service-payment]
verify_jwt = false

[functions.create-manual-payment-link]
verify_jwt = false

[functions.create-mp-payment]
verify_jwt = false

[functions.mp-payment-status]
verify_jwt = false

[functions.process-approved-payment]
verify_jwt = false

[functions.mp-payment-webhook]
verify_jwt = false

[functions.send-cashback-notification]
verify_jwt = false

[functions.check-expiring-cashback]
verify_jwt = false

[functions.create-partner-user]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.generate-churn-message]
verify_jwt = false

[functions.process-document-expiration]
verify_jwt = false

[functions.update-partner-password]
verify_jwt = false

[functions.ai-admin-response]
verify_jwt = false

[functions.analyze-dre]
verify_jwt = false
